### ISSUE TITLE
Delay-load device-specific DLLs

### ISSUE THREAD

**Issue by Sunderlandkyl** [PlusToolkit/PlusBuild#11]
Some devices rely on various driver DLLs that are installed in system directories. If those DLLs are not installed then none of the Plus application start. Using delayed DLL loading the driver DLLs would not be required unless that specific device is used that requires that DLL.

https://msdn.microsoft.com/en-us/library/151kt790(v=vs.90).aspx

Offending devices:
- Interson US
- Telemed US
- Thorlabs spectrometer
- MicronTracker (on WinXP embedded)

This would mean that a single package could be used on all configurations. Multiple packages would be still needed to cover different SDK versions (Ultrasonix and MicronTracker) and Win32/Win64.

Migrated from https://app.assembla.com/spaces/plus/tickets/1005/details

**Comment by dzenanz** [comment]
I think this is true for other devices besides those you listed, e.g. Capistrano US, USDigital encoders etc.

**Comment by Sunderlandkyl** [comment]
This issue was moved to PlusToolkit/PlusLib#232
